# Generated by Django 4.0.5 on 2022-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctions_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='description',
        ),
        migrations.AddField(
            model_name='auctions',
            name='Auction_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
