# Generated by Django 4.0.5 on 2022-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auctions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='Auction_price',
            field=models.IntegerField(null=True),
        ),
    ]
