# Generated by Django 4.0.5 on 2022-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctions_auction_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='auctions',
            name='Auction_category',
            field=models.DateField(null=True),
        ),
    ]
