# Generated by Django 4.0.5 on 2022-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_delete_category_auctions_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='Auction_category',
            field=models.SlugField(null=True),
        ),
    ]
