# Generated by Django 4.0.5 on 2022-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctions_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='Auction_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
