# Generated by Django 4.0.5 on 2022-07-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctions_auction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='Auction_image',
        ),
    ]
