# Generated by Django 4.0.5 on 2022-07-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_alter_auctions_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='Auction_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
