# Generated by Django 4.0.5 on 2022-07-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_alter_auctions_auction_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='Auction_image',
            new_name='auction_image',
        ),
    ]
