# Generated by Django 4.0.5 on 2022-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_rename_auction_image_auctions_auction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ManyToManyField(blank=True, related_name='comment', to='auctions.auctions')),
            ],
        ),
    ]
