# Generated by Django 4.0.5 on 2022-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
