# Generated by Django 4.0.5 on 2022-08-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0055_remove_comments_name_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
