# Generated by Django 4.0.5 on 2022-08-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0056_remove_comments_user_comments_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='auction',
        ),
    ]
