# Generated by Django 4.0.5 on 2022-08-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='auctions.auctions'),
        ),
    ]
