# Generated by Django 4.0.5 on 2022-08-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0060_categories_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='auction',
            new_name='auctions',
        ),
    ]
