# Generated by Django 4.0.5 on 2022-08-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0064_alter_comments_options_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='auction',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='Auction_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
    ]
