# Generated by Django 4.0.5 on 2022-08-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0067_auctions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='Auction_category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
