# Generated by Django 4.0.5 on 2022-08-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0069_categories_auctions_auction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='user',
        ),
    ]
