# Generated by Django 4.0.5 on 2022-08-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0071_remove_auctions_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='Auction_category',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
