# Generated by Django 4.0.5 on 2022-08-08 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0072_auctions_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
