# Generated by Django 4.0.5 on 2022-08-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0073_auctions_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
