# Generated by Django 4.0.5 on 2022-08-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0076_alter_auctions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
