# Generated by Django 4.0.5 on 2022-08-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0079_alter_auctions_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='Auction_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
    ]
