# Generated by Django 4.0.5 on 2022-08-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0082_alter_auctions_auction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='auction_image',
            new_name='Auction_image',
        ),
    ]
