# Generated by Django 4.0.5 on 2022-08-09 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0083_rename_auction_image_auctions_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, related_name='auction_watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
