# Generated by Django 4.0.5 on 2022-08-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0087_remove_price_auctions_auctions_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='auction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
    ]
