# Generated by Django 4.0.5 on 2022-08-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0088_remove_auctions_price_price_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='auction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
    ]
