# Generated by Django 4.0.5 on 2022-08-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0091_alter_price_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='auction',
        ),
    ]
