# Generated by Django 4.0.5 on 2022-08-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0092_remove_price_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctions'),
        ),
    ]
