# Generated by Django 4.0.5 on 2022-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0098_alter_auctions_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='Auction_price',
            field=models.FloatField(null=True),
        ),
    ]
